### ISSUE TITLE
Path to Vagrant's private key file is wrapped in a spare set of quotes

### ISSUE THREAD

**Issue by benlk** [INN/deploy-tools#39]
Running OSX 10.10.5 (14F1605) with Python 2.7.10 and the latest version of everything in [the largo umbrella's requirements.txt](https://bitbucket.org/projectlargo/largo-umbrella/src/0eb51346677099b15955cf5b2c393cde1b33a08b/requirements.txt?fileviewer=file-view-default) in a virtualenv, Fabric is unable to find the private key file created by Vagrant/Virtualbox in order to access the VM:

```
(largo)blk@oyster:~/inn/vms/umbrella$ fab dev wp.tests.setup:largo-dev
[192.168.33.10] Executing task 'wp.tests.setup'
Setting up tests for largo-dev...
Traceback (most recent call last):
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/tasks.py", line 368, in execute
    multiprocessing
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/tasks.py", line 264, in _execute
    return task.run(*args, **kwargs)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/tasks.py", line 171, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/blk/inn/vms/umbrella/tools/fablib/wp/tests.py", line 31, in setup
    plugins = json.loads(helpers.capture('wp plugin list --format=json --fields=name', cmd_type='run'))
  File "/Users/blk/inn/vms/umbrella/tools/fablib/helpers.py", line 148, in capture
    result = run(cmd)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/network.py", line 639, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/operations.py", line 1042, in run
    shell_escape=shell_escape)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/operations.py", line 909, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/state.py", line 388, in default_channel
    chan = _open_session()
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/state.py", line 380, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/network.py", line 151, in __getitem__
    self.connect(key)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/network.py", line 143, in connect
    self[key] = connect(user, host, port, cache=self)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/fabric/network.py", line 444, in connect
    sock=sock
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/paramiko/client.py", line 273, in connect
    self._auth(username, password, pkey, key_filenames, allow_agent, look_for_keys)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/paramiko/client.py", line 387, in _auth
    key = pkey_class.from_private_key_file(key_filename, password)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/paramiko/pkey.py", line 177, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/paramiko/rsakey.py", line 51, in __init__
    self._from_private_key_file(filename, password)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/paramiko/rsakey.py", line 161, in _from_private_key_file
    data = self._read_private_key_file('RSA', filename, password)
  File "/Users/blk/.virtualenvs/largo/lib/python2.7/site-packages/paramiko/pkey.py", line 249, in _read_private_key_file
    f = open(filename, 'r')
IOError: [Errno 2] No such file or directory: '"/Users/blk/inn/vms/umbrella/.vagrant/machines/default/virtualbox/private_key"'
(largo)blk@oyster:~/inn/vms/umbrella$ ll /Users/blk/inn/vms/umbrella/.vagrant/machines/default/virtualbox/private_key
-rw-------  1 blk  staff   1.6K May 14  2015 /Users/blk/inn/vms/umbrella/.vagrant/machines/default/virtualbox/private_key
```

At the bottom, we see that the file exists at the path specified, and that the path is being wrapped in a set of `""` double quotes for some reason.

**Comment by benlk** [comment]
```
blk@silverleaf:/media/blk/DATA/VM/umbrella$ vagrant --version
Vagrant 1.6.2

blk@silverleaf:/media/blk/DATA/VM/umbrella$ vagrant ssh-config
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/blk/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

```
Note the lack of `""`.

So yes, Vagrant's output changed, and as a result deploy-tools broke. This issue will affect anyone who upgrades their Vagrant or uses newer versions of Vagrant on a clean install.
